---
driver:
  name: vagrant
  customize:
     memory: 3072
provisioner:
  name: chef_solo
  require_chef_omnibus: 12.21.14
  solo_rb:
    environment: local
platforms:
  - name: centos-7.2

suites:
  - name: testing
    run_list:
      - recipe[httpd_deploy]

